export const REQUEST_PENDING = 'REQUEST_PENDING';

export const COUNTER_INC = 'COUNTER_INC';
export const COUNTER_DEC = 'COUNTER_DEC';

export const COUNTER_REQUEST_PENDING = 'COUNTER_REQUEST_PENDING';
export const COUNTER_REQUEST_FAILURE = 'COUNTER_REQUEST_FAILURE';
export const COUNTER_REQUEST_SUCCESS = 'COUNTER_REQUEST_SUCCESS';
